### ISSUE TITLE
Set max-width for desktop browsers

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/shitty-vegan#14]
Add max widths so that it looks nice on a lappy

**Comment by oliverjam** [comment]
This might need a bit of design thought. The layout doesn't work super well even with a max-width: might be better to rearrange to a horizontal layout with the calendar on the left and feedback on the right

**Comment by Jamchiller** [comment]
Yeah true, but thought putting any more thought into it would constitute a Post-MVP issue, and saw this as a quick fix - ie, essentially displaying at mobile aspect ratio regardless of browser width. 

However if you're happy to do the dev then I can put together a design! Let me know and I will add it to my to do list

**Comment by oliverjam** [comment]
Yeah I could just lock it to 320px or whatever so you can at least use it as if you were on a phone on desktop. Probably not MVP so don't prioritise the responsive designs

**Comment by Jamchiller** [comment]
Perfect yeah, just lock it for now, responsive is post-MVP. I'll chuck in backlog

**Comment by oliverjam** [comment]
I remembered why it wasn't as simple as locking the width...

Blue is the mobile-width container—the calendar is overflowing out because I had to hard-code the day-squares widths/heights to ensure they stayed actually square
<img width="916" alt="screen shot 2018-08-20 at 22 54 23" src="https://user-images.githubusercontent.com/9408641/44368821-0fca4d00-a4cc-11e8-85bb-3c4bfd7e5e7d.png">

**Comment by oliverjam** [comment]
Okay got an ugly hack working where after a certain point I just fix the size of the day squares

<img width="1792" alt="screen shot 2018-08-20 at 23 15 54" src="https://user-images.githubusercontent.com/9408641/44369793-89b00580-a4cf-11e8-986f-cad7c2ac8c46.png">

![responsive-cal](https://user-images.githubusercontent.com/9408641/44369836-af3d0f00-a4cf-11e8-8c54-7a4a2a1643e2.gif)

**Comment by Jamchiller** [comment]
Perfect! Done diddly done
